version: "3.5"

services:
  api01: &api
    build:
      context: .
      target: final
    hostname: api01
    environment:
      DATABASE_URL: postgres://myuser:mypass@db/showdown_db
    # expose:
    #  - 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      DATABASE_URL: postgres://myuser:mypass@db/showdown_db
    ports:
      - "3001:3000"

  db:
    image: postgres:16.2-alpine3.18
    volumes:
      - ./db_init_script.sql:/docker-entrypoint-initdb.d/db_init_script.sql
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: showdown_db
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300MB"

  nginx:
    image: nginx:1.25.4-alpine3.18
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1